title: James Allan Hall
subtitle: "Data Scientist | Product Manager"

description: #>- # this means to ignore newlines until "baseurl:"
  "Data Science Portfolio"
  
author: "James Allan Hall"
email: "jallanhall@gmail.com"
avatar: "assets/images/headshot.jpg"

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamjahal.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: 'https://twitter.com/AllanHall1'
facebook_url: 'https://facebook.com/jamesallanhall'
googleplus_url:
instagram_url:
linkedin_url: 'https://linkedin.com/in/james-allan-hall'
github_url: 'github.com/jamjahal'
pinterest_url:
slack_url:
dribbble_url:

  
# Google Analytics Tracking ID goes here:
google_analytics: <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145609977-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-145609977-3');
</script>



# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: jamjahal/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed
collections: [sections]
